FROM python:3.8.6-alpine3.12
LABEL maintainer="bhakti"
#set working dir for container workign dir will create in alpine container
WORKDIR /usr/src/app
#copy the python frm host to 
COPY pythonD.py .
CMD ["python3", "pythonD.py"]

