#print hello message instide a container
FROM ubuntu:20.04
#mainainer
LABEL maintainer="bhaktinikam97@gmail.com"
#command can exeute in base image using bash shell
CMD ["echo", "Hello world from Docker"]
#CMD echo "hello world form docker"

