#calculator application
FROM python:3.8.6-alpine3.12
#maintainer
LABEL maintainer = "Bhakti Nikam"
#workdir
WORKDIR /usr/src/cloudassesment
#COPY FROM HOTS TO CONTAINER
COPY python.py .
CMD ["python3", "python.py"]
